### PR TITLE
Villingen-Schwenningen changed the software to koha

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by raphaelm** [comment]
Has this been tested with the app?

**Comment by ostcar** [comment]
No. I just used the values I found in simular PRs.

How can I Test this with the App? I have no expirience with App development

**Comment by ostcar** [comment]
I have tested, that the current version does not work at all. So this change can not make it worse

**Comment by ostcar** [comment]
Is there anything I can do to speedup this PR?

By the way, I really love your app. I read your messages, that you need commercial support and I already ask the responsible person to sign a contract with you. But for the moment, this PR is everything I can do.

**Comment by raphaelm** [comment]
Has been fixed in the meantime :)

**Pull request closed without merging**
